### ISSUE TITLE
simcse and llama tokenizer compatibility

### ISSUE THREAD

**Issue by KahimWong** [mignonjia/TS_watermark#2]
Hi, it seems the tokenizers of simcse and llama are not compatible, the size of vocab is different. How the model work in this case?

**Comment by mignonjia** [comment]
Thanks for your interest! 
Our model is trained on the OPT model, which uses the same tokenizer as SimCSE. We evaluate the model's performance on LLaMA. Given the current tokens in LLaMA, we convert them to text, then re-tokenize them using the OPT tokenizer. This allows us to leverage our pre-trained gamma and delta generators to obtain the gamma and delta values. For detailed implementation, check the code [here](https://github.com/mignonjia/TS_watermark/blob/main/watermark_processor_llama.py#L141). SimCSE is evaluated also in this way, and the code is [here](https://github.com/mignonjia/TS_watermark/blob/main/inference_llama.py#L393).
